[package]
name = "dovecot-nextcloud-auth"
version = "0.1.0"
authors = ["Thomas Oettli <spacefreak@noop.ch>"]
edition = "2021"

[profile.release]
lto = true
codegen-units = 1

[dependencies]
mysql = "*"
config-file = "*"
serde = { version="*", features=["derive"]}
nix = "*"
phf = { version="*", features=["macros"]}
ureq = "*"
base64 = "*"
