configured = false
db_url = 'mysql://DBUSER:DBPASS@localhost:3306/postfix'

[lookup_module]
type = 'DB'
user_query = "SELECT maildir AS home, CONCAT('maildir:', maildir) as mail, uid, gid, CONCAT('*:bytes=', quota) AS quota_rule, password FROM mailbox WHERE username = :username AND active = '1'"

[verify_module]
type = 'Http'
url = 'https://localhost/auth'
method = 'GET'
ok_code = 200
invalid_code = 403

[verify_cache_module]
type = 'DB'
db_table = 'password_cache'
verify_interval = 60
max_lifetime = 86400
cleanup = true
hash_scheme = 'SSHA512'
allow_expired_on_error = false

[update_credentials_module]
type = 'DB'
update_password_query = 'UPDATE mailbox SET password = :password WHERE username = :username'
hash_scheme = 'SSHA512'
